version: '3'
services:
  node:
    build: 
        context: ./
        dockerfile: ./src/Dockerfile
    working_dir: /home/node/app/src
    volumes:
      - ./:/home/node/app
    ports:
      - 3001:3000
    environment:
      - HOST=0.0.0.0