version: '3'
services:
  node:
    build: 
        context: ./
        dockerfile: ./project/Dockerfile
    working_dir: /home/node/app/project
    volumes:
      - ./:/home/node/app
    ports:
      - 8000:3000
    environment:
      - HOST=0.0.0.0